# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afrog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afrog.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=600)),
                ('link', models.URLField(max_length=60)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('projimage', models.ImageField(blank=True, upload_to='postimages/')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afrog.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afrog.Project'),
        ),
    ]
